version: '3'

services:

  nodejs-monetiz:
    container_name: nodejs-monetiz
    build: '.'
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    depends_on:
      - postgres-monetiz
    networks:
      - app-connect
    ports:
      - '3333:3333'

  postgres-monetiz:
    container_name: postgres-monetiz
    image: postgres:11
    restart: unless-stopped
    volumes:
      - postgres-monetiz-data:/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - app-connect

volumes:
  postgres-monetiz-data:

networks:
  app-connect:
      driver: bridge
