version: '3'

services:
  web:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - /app/node_modules
      - .:/app

  database:
    image: postgres:11
    ports:
      - "5432:5432"
    env_file:
    - ./.env
    environment:
      POSTGRES_DB: monetiz
      POSTGRES_USER: desafio
      POSTGRES_PASSWORD: desafio
      POSTGRES_PORT: 5432

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
